name: Build

on:
  push:
    branches: [develop]
  release:
    types: [published]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
        with:
          images: swissgrc/azure-pipelines-renovate
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            # set unstable tag for develop branch
            type=raw,value=unstable,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}

      # Build Docker image with Buildx
      - name: Build Docker image
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 # v3.3.0
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Scan Docker image (not for release builds since we will have multiple tags)
      - name: Scan Docker image
        if: github.event_name != 'release'
        uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5 # tag=0.8.0
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Publish scan report to GitHub
      - name: Publish scan report to GitHub        
        if: ${{ github.event_name != 'release' && always() }}
        uses: github/codeql-action/upload-sarif@436dbd9100756e97f42f45da571adeebf8270723 # v2.2.0
        with:
          sarif_file: trivy-results.sarif

      # Login to Docker registry if not PR build
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Publish Docker image for CI builds if not PR build
      - name: Push container image
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 # v3.3.0
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Update Readme on Docker Hub
      - name: Publish README to Docker Hub
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@93b93397c27ed52b4055b8c6b2f8d92456ab3c56 # v3.1.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: swissgrc/azure-pipelines-renovate
